version: "3"
services:
  django:
    container_name: odontologia
    build:
      context: .
      dockerfile: Dockerfile
    image: odontologia:1.0    
    stdin_open: true
    tty: true
    volumes:
      - .:/var/www/odontologia
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql  
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: odontoq1w2e3
      MYSQL_DATABASE: webodonto
      MYSQL_USER: userodonto
      MYSQL_PASSWORD: odontoq1w2e3
      MYSQL_HOST: localhost
    ports:
      - "3306:3306"
