version: "3"
services:
  django:
    container_name: odontologia
    build:
      context: .
      dockerfile: Dockerfile
    image: odontologia:1.0    
    stdin_open: true
    tty: true
    volumes:
      - .:/var/www/odontologia
    ports:
      - "8000:8000"
